DROP TABLE IF EXISTS PREFECTURE CASCADE;
DROP TABLE IF EXISTS VALISE CASCADE;

CREATE TABLE PREFECTURE (
  ID_PREFECTURE SERIAL PRIMARY KEY
  , REGION TEXT NOT NULL
  , DEPARTEMENT TEXT NOT NULL
  , PREFECTURE TEXT UNIQUE NOT NULL
  , ADRESSE TEXT NOT NULL
  , CODE_POSTAL INTEGER NOT NULL
  , VILLE TEXT NOT NULL
);

CREATE TABLE VALISE (
  NUM_VALISE INTEGER PRIMARY KEY
  , DATE_VALISE DATE NOT NULL
);

INSERT INTO PREFECTURE (REGION, DEPARTEMENT, PREFECTURE, ADRESSE, CODE_POSTAL, VILLE) VALUES ('PAYS DE LA LOIRE', 'LOIRE ATLANTIQUE', 'NANTES', 'MAIRIE', 44000, 'NANTES');
INSERT INTO PREFECTURE (REGION, DEPARTEMENT, PREFECTURE, ADRESSE, CODE_POSTAL, VILLE) VALUES ('SEINE SAINT DENIS', 'ILE DE FRANCE', 'SEVRAN', 'MAIRIE', 93270, 'SEVRAN');

INSERT INTO VALISE (NUM_VALISE, DATE_VALISE) VALUES (350, TO_DATE('17/05/2018', 'DD/MM/YYYY'));
INSERT INTO VALISE (NUM_VALISE, DATE_VALISE) VALUES (450, TO_DATE('17/05/2018', 'DD/MM/YYYY'));
INSERT INTO VALISE (NUM_VALISE, DATE_VALISE) VALUES (550, TO_DATE('30/05/2018', 'DD/MM/YYYY'));
INSERT INTO VALISE (NUM_VALISE, DATE_VALISE) VALUES (650, TO_DATE('31/05/2018', 'DD/MM/YYYY'));
INSERT INTO VALISE (NUM_VALISE, DATE_VALISE) VALUES (750, TO_DATE('25/06/2018', 'DD/MM/YYYY'));
INSERT INTO VALISE (NUM_VALISE, DATE_VALISE) VALUES (950, TO_DATE('29/06/2018', 'DD/MM/YYYY'));



COMMIT;
