ALTER TABLE PERMIS_MVF ADD UNIQUE (ID_PERSONNE_MVF, NUM_PERMIS);
ALTER TABLE PERMIS_MVF ADD CONSTRAINT PERSONNE_PERMIS_FK FOREIGN KEY (ID_PERSONNE_MVF)
 REFERENCES PERSONNE_MVF (ID_PERSONNE_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PERMIS_MVF ADD CONSTRAINT DOSSIER_PERMIS_FK FOREIGN KEY (ID_DOSSIER_MVF)
 REFERENCES DOSSIER_MVF (ID_DOSSIER_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE PERMIS_MVF ADD CONSTRAINT COPIEPERMIS_PERMIS_FK FOREIGN KEY (ID_COPIE_PERMIS_MVF)
 REFERENCES COPIE_PERMIS_MVF (ID_COPIE_PERMIS_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE COPIE_PERMIS_MVF ADD CONSTRAINT PERMIS_COPIEPERMIS_FK FOREIGN KEY (ID_PERMIS_MVF)
 REFERENCES PERMIS_MVF (ID_PERMIS_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE PERSONNE_MVF ADD CONSTRAINT PERMIS_PERSONNE_FK FOREIGN KEY (ID_PERMIS_MVF)
 REFERENCES PERMIS_MVF (ID_PERMIS_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE DOSSIER_MVF ADD CONSTRAINT PERMIS_DOSSIER_FK FOREIGN KEY (ID_PERMIS_MVF)
 REFERENCES PERMIS_MVF (ID_PERMIS_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE DOSSIER_MVF ADD CONSTRAINT PREFECTURE_DOSSIER_FK FOREIGN KEY (ID_PREFECTURE_ENVOI)
 REFERENCES PREFECTURE (ID_PREFECTURE) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE DOSSIER_MVF ADD CONSTRAINT COPIEDEMANDE_DOSSIER_FK FOREIGN KEY (ID_COPIE_DEMANDE_PREFECTURE_MVF)
 REFERENCES COPIE_DEMANDE_PREFECTURE_MVF (ID_COPIE_DEMANDE_PREFECTURE_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE COPIE_DEMANDE_PREFECTURE_MVF ADD CONSTRAINT DOSSIER_COPIEDEMANDE_FK FOREIGN KEY (ID_DOSSIER_MVF)
 REFERENCES DOSSIER_MVF (ID_DOSSIER_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE NOTE_VERBALE_PERMIS_MVF ADD UNIQUE (ID_PERMIS_MVF, ID_NOTE_VERBALE_MVF);
ALTER TABLE NOTE_VERBALE_PERMIS_MVF ADD CONSTRAINT PERMIS_NOTE_PERMIS_FK FOREIGN KEY (ID_PERMIS_MVF)
 REFERENCES PERMIS_MVF (ID_PERMIS_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE NOTE_VERBALE_PERMIS_MVF ADD CONSTRAINT NOTE_NOTE_PERMIS_FK FOREIGN KEY (ID_NOTE_VERBALE_MVF)
 REFERENCES NOTE_VERBALE_MVF (ID_NOTE_VERBALE_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE ATTESTATION_MVF ADD CONSTRAINT PERMIS_ATTESTATION_FK FOREIGN KEY (ID_PERMIS_MVF)
 REFERENCES PERMIS_MVF (ID_PERMIS_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ATTESTATION_MVF ADD CONSTRAINT COPIEATTESTATION_ATTESTATION_FK FOREIGN KEY (ID_COPIE_ATTESTATION_MVF)
 REFERENCES COPIE_ATTESTATION_MVF (ID_COPIE_ATTESTATION_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE ATTESTATION_MVF ADD CONSTRAINT COPIENOTE_ATTESTATION_FK FOREIGN KEY (ID_COPIE_NOTE_VERBALE_MAECI_MVF)
 REFERENCES COPIE_NOTE_VERBALE_MAECI_MVF (ID_COPIE_NOTE_VERBALE_MAECI_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE COPIE_ATTESTATION_MVF ADD CONSTRAINT ATTESTATION_COPIEATTESTATION_FK FOREIGN KEY (ID_ATTESTATION_MVF)
 REFERENCES ATTESTATION_MVF (ID_ATTESTATION_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE COPIE_NOTE_VERBALE_MAECI_MVF ADD CONSTRAINT ATTESTATION_COPIENOTE_FK FOREIGN KEY (ID_ATTESTATION_MVF)
 REFERENCES ATTESTATION_MVF (ID_ATTESTATION_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE BORDEREAU_ATTESTATION_MVF ADD UNIQUE (ID_ATTESTATION_MVF, ID_BORDEREAU_MVF);
ALTER TABLE BORDEREAU_ATTESTATION_MVF ADD CONSTRAINT ATTESTATION_BORDEREAU_ATTESTATION_FK FOREIGN KEY (ID_ATTESTATION_MVF)
 REFERENCES ATTESTATION_MVF (ID_ATTESTATION_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE BORDEREAU_ATTESTATION_MVF ADD CONSTRAINT BORDEREAU_BORDEREAU_ATTESTATION_FK FOREIGN KEY (ID_BORDEREAU_MVF)
 REFERENCES BORDEREAU_MVF (ID_BORDEREAU_MVF) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

ALTER TABLE BORDEREAU_MVF ADD CONSTRAINT VALISE_BORDEREAU_FK FOREIGN KEY (NUM_VALISE)
 REFERENCES VALISE (NUM_VALISE) ON DELETE CASCADE DEFERRABLE INITIALLY DEFERRED;

COMMIT;
