DROP TABLE IF EXISTS ROLE_UTILISATEUR CASCADE;
DROP TABLE IF EXISTS ROLE CASCADE;
DROP TABLE IF EXISTS UTILISATEUR CASCADE;
DROP TABLE IF EXISTS PERMIS CASCADE;
DROP TABLE IF EXISTS PERSONNE CASCADE;
DROP TABLE IF EXISTS DOSSIER CASCADE;
DROP TABLE IF EXISTS PREFECTURE CASCADE;
